### ISSUE TITLE
Creating partial for whitelist

### ISSUE THREAD

**Issue by grctest** [grctest/Gridcoin-Site#16]
We should create a partial snippet of code for the whitelist, so that we do not have to make whitelist code changes in 3 places but rather only in the one place.

Similar partials we currently use:
https://github.com/grctest/Gridcoin-Site/tree/master/source/layouts/partials

**Comment by barton2526** [comment]
working on implementation

**Comment by grctest** [comment]
I've removed the whitelist from the index page and the guides, it remains solely within the dedicated whitelist page. We could still make a partial so that it can be reused in the future though.

**Comment by grctest** [comment]
Created a partial for the whitelist:
https://github.com/grctest/Gridcoin-Site/blob/master/source/layouts/partials/_whitelist.erb
