### ISSUE TITLE
Refactoring/Condensing the Pool/Investor/Solo guides

### ISSUE THREAD

**Issue by grctest** [grctest/Gridcoin-Site#17]
Currently, the 3 main guides are very 'wall-of-texty'; condensing the information to be easier to read would be highly beneficial for new users.

The light grey text on dark background also is perhaps difficult to read, we may have to rethink the website's theme to improve accessibility.

**Comment by grctest** [comment]
I'd really appreciate some help improving these guides, thanks.

**Comment by startailcoon** [comment]
I've started a section on the Wiki to expand on. The current mining guides are a little messy and doesn't explain the difference of Staking and DPoR, as well as that you don't have to mine. We can make that better and then go to formatting it to the main page?

I can write How-To documents and screenshots.

[Setting up the Wallet](http://wiki.gridcoin.us/Wallet_setup) - Work in Progress

**Comment by grctest** [comment]
I have heavily edited the 3 guides

**Comment by barton2526** [comment]
Is this finished @grctest ?

**Comment by grctest** [comment]
The final page for investor is quite bare, perhaps it needs additional info or could be placed on the 2nd page?

Pretty ugly, lol:
![image](https://user-images.githubusercontent.com/15861527/27509311-9b67cbb2-58f1-11e7-988f-12f968ebd6c4.png)
