### ISSUE TITLE
in top menu: add a link titled wallet

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [grctest/Gridcoin-Site#19]
normally coin pages have on top a link called: wallet
and there you find the downloads for: desktop, smart phones, ...

why important ?
* newcomers just want to try first, without reading
* other sites also have such a prominent button

**Comment by grctest** [comment]
I've added a small cloud-download icon to the nav bar as a direct link to the client downloads.
Not live at the moment, but it'll be in the next commit.
Thanks for the suggestion.
