### ISSUE TITLE
Change inline css to proper stylesheets where appropriate

### ISSUE THREAD

**Issue by barton2526** [grctest/Gridcoin-Site#33]
Too many pages rely on inline CSS.  This is inefficient and needs to be refactored.

**Comment by grctest** [comment]
I have removed a lot of the inline CSS, what's left can likely be smashed into a CSS file.

We could make use of more partials to reduce replicated code.

**Comment by grctest** [comment]
This issue was moved to gridcoin-community/Gridcoin-Site#5
