### ISSUE TITLE
Remove Demo Images / Files that came with KIT

### ISSUE THREAD

**Issue by barton2526** [grctest/Gridcoin-Site#36]
These will have to be carefully refactored to ensure nothing breaks.

**Comment by barton2526** [comment]
Removed some demo css lines in my last PR.

**Comment by grctest** [comment]
I've removed the majority of the images within the asset folder, they  were unnecessary.

**Comment by barton2526** [comment]
Can this be closed?

**Comment by barton2526** [comment]
Move to close @grctest

**Comment by barton2526** [comment]
See #69
