### ISSUE TITLE
Whitelist Page - Header Spacing

### ISSUE THREAD

**Issue by jimbo-slice** [grctest/Gridcoin-Site#41]
Hey guys, the new site looks great, I'm reading through the new guides now. I did notice that on the [whitelist page](https://gridcoin.us/Guides/whitelist.htm) the header seems to be too low (or, the body too high). I've attached a screenshot.
![whitelist](https://user-images.githubusercontent.com/26789781/27517931-78246186-5989-11e7-9032-2b900c0e28a6.png)

**Comment by barton2526** [comment]
@grctest does this page have the same header padding as the others?

**Comment by grctest** [comment]
It does not appear to have the correct padding, no:
[Whitelist partial](https://github.com/grctest/Gridcoin-Site/blob/master/source/layouts/partials/_whitelist.erb#L14)
`<section data-background-color="black" style="padding-bottom:0px; margin-top:-20px; padding-top: 73px;">`

[Comparison section](https://github.com/grctest/Gridcoin-Site/blob/master/source/Guides/acquire-grc.htm.erb)
`<section data-background-color="black" style="padding-bottom: 5px; padding-top:60px; margin-top: 0px;">`

I'll look into fixing this, thanks for reporting this issue @jimbo-slice

**Comment by jimbo-slice** [comment]
@grctest cool! yah, no problem
