### ISSUE TITLE
Index page - improving readability

### ISSUE THREAD

**Issue by grctest** [grctest/Gridcoin-Site#42]
>The user '[@ponimayu](https://steemit.com/gridcoin/@cm-steem/upgraded-the-gridcoin-us-website-w-help-from-barton26-and-peppernrino#@ponimayu/re-cm-steem-re-cm-steem-upgraded-the-gridcoin-us-website-w-help-from-barton26-and-peppernrino-20170625t143855066z)' posted the following in the [recent Steemit thread]():
>> I like the nav changes, but I think the old pages looked neater and more organized, more pleasing to the eye, easier to scan for info. Especially the features section. I cannot speak to the content changes (yet).

Difference: (Left old, Right current)
![image](https://user-images.githubusercontent.com/15861527/27518506-7bac22d0-59d9-11e7-910f-46566a181839.png)

I do agree that it is rather monotone and wall-of-text like, perhaps changing the background of the features section would improve readability?

Would bringing the circle icons/logos make it look better?
Should we change the contents of this section of the index page?

Thoughts anyone?

**Comment by grctest** [comment]
Added a lighter background so as to improve readability, thoughts?

![image](https://user-images.githubusercontent.com/15861527/27603905-91156cca-5b6f-11e7-9a0e-2094e45f4481.png)

**Comment by jimbo-slice** [comment]
I agree with OP on this one. The borders, icons, and colors break it up into easily consumable portions and it is a lot easier on the eye.

**Comment by grctest** [comment]
This issue was moved to gridcoin-community/Gridcoin-Site#4
