### ISSUE TITLE
Whitelist Typos/Formatting

### ISSUE THREAD

**Issue by jimbo-slice** [grctest/Gridcoin-Site#49]
https://gridcoin.us/Guides/whitelist.htm

1) The project link for LHC@Home should be changed to this: https://lhcathome.cern.ch/lhcathome/index.php and the team link should be changed to this: https://lhcathome.cern.ch/lhcathome/team_display.php?teamid=8128

2) For Numberfields@Home, in the "Goal" column, we need a period or semicolon after "Research in number theory"

3) For Universe@Home, the "Sponsor" column should say University of Warsaw instead of University of Warsow"

4) For Amicable Numbers, the second sentence in the "Goal" column is unnecessary. 

5) For Collatz Conjecture, the word "private" needs to be removed from the "Goal" column and added to the "Sponsor" column. 

6) For YAFU and AmicableNumbers, the "Sponsor" column should say "private" instead of "N/A", so it fits the format of the other projects that aren't backed by a university or organization.

A few notes on formatting:

1) I think we should sort A-Z by project name.

2) I think it would look a lot better if we vertically aligned this data at the bottom or the middle of each cell, instead of at the top.

**Comment by barton2526** [comment]
All issues resolved.  Formatting changes pending @grctest 

https://github.com/grctest/Gridcoin-Site/pull/51

**Comment by jimbo-slice** [comment]
@barton2526 Thanks for doing this. I'm still new and haven't yet figured out the pull-request process.

Regarding formatting, if @grctest disagrees with my changes, at the very least we should move TN-Grid up the list to be with the other CPU-only projects.

**Comment by barton2526** [comment]
My latest PR #56 moves TN-Grid to be in the CPU section

**Comment by barton2526** [comment]
Move to Close.  @grctest
