### ISSUE TITLE
Front Page Typos/Formatting

### ISSUE THREAD

**Issue by jimbo-slice** [grctest/Gridcoin-Site#50]
https://gridcoin.us/

1) Solo/Pool Crunching comparison section:
![solo-pool](https://user-images.githubusercontent.com/26789781/27844089-832a5ce4-60d1-11e7-931c-9a3651efc7a9.png)
a) The alignment looks odd. The Solo section starts much lower than the pool section
b) Under Solo Crunching, the last sentence should start with "A" instead of "An". Also in the last sentence, "Gridcoin" should be capitalized.
c) Under Pool Crunching, the second sentence: "Gridcoin" should be capitalized and "GRC" should just be "Gridcoin" since the acronym wasn't used anywhere else in this section.

2) Proof of Stake section:
![pos](https://user-images.githubusercontent.com/26789781/27844182-df112208-60d2-11e7-9b08-eff08b61c633.png)
a) This sentence is really weird: "You can vote using your balance to vote on important matters within the Gridcoin client." Perhaps it should be something like this: "You can vote on important community initiatives within the Gridcoin client".

3) Features section:
![features](https://user-images.githubusercontent.com/26789781/27844236-74da6768-60d3-11e7-84b4-665590b7c6bf.png)
a) Under proof-of-stake, "gridcoin" should be capitalized. 
b) Under proof-of-boinc, replace the acronym "GRC" with "Gridcoin", for consistency.
c) Under boinc whitelist section, there are a few issues. Here's my rewrite:
Gridcoin has implemented a BOINC project whitelist to improve security. Each BOINC project must meet certain criteria to be whitelisted, and no Gridcoin rewards will be given on behalf of projects that fail to meet our security standards.
d) Under DPOR section, replace "GRC" with "Gridcoin" for consistency.
e) Under Help Advance Science section, I fixed a few typos and changed a few sentences:
With Gridcoin, not only will you be rewarded financially, but you'll also be supporting important research projects. These projects are working toward a wide range of goals, such as disease research and eradication (cancer, AIDS, Ebloa, Malaria, and others), mapping the Milkyway, and improving our understanding of mathematics. 
Your participation will also help establish and strengthen the Gridcoin economy. A strong market will help to push volunteer computing into the mainstream and will provide much needed support for scientific research.
f) I also think we should return to the old block-style format, shown in issue #42

**Comment by barton2526** [comment]
1b and 1c are fixed.
2a is corrected.
3a, 3b, 3c, 3d, 3e corrected.

https://github.com/grctest/Gridcoin-Site/pull/51

@grctest 1a and 3f remain.

**Comment by jimbo-slice** [comment]
@barton2526 thank you very much!

Let's close this after 1a is solved, as 3f just refers to open issue #42. No need to have the same issue listed twice.

**Comment by grctest** [comment]
This issue was moved to gridcoin-community/Gridcoin-Site#3
