### ISSUE TITLE
Opensuse & Fedora issue

### ISSUE THREAD

**Issue by grctest** [grctest/Gridcoin-Site#54]
><@marix> So I just realised, the link for the openSUSE and Fedora packages on gridcoin.us should probably rather be https://software.opensuse.org/search?utf8=✓&q=gridcoin&search_devel=false&search_unsupported=false.
><@marix> Or even https://software.opensuse.org/package/gridcoinresearch.

**Comment by barton2526** [comment]
Addressed in #69.  Move to close @grctest
